### ISSUE TITLE
Auto clicker doesn't work. 

### ISSUE THREAD

**Issue by devxan** [tesilio/auto-clicker#4]
@tesilio Auto clicker doesn't work on [https://scratch.mit.edu/projects/47614000/](https://scratch.mit.edu/projects/47614000/).

**Comment by tesilio** [comment]
Sorry, but this extension doesn't work on canvas elements.

**Comment by devxan** [comment]
> Sorry, but this extension doesn't work on canvas elements.

@tesilio 😭 maybe update it so it can?
